// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list_ideas.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_ideas_default = defineTool({
  name: "list_ideas",
  title: "\u0421\u043F\u0438\u0441\u043E\u043A \u0438\u0434\u0435\u0439",
  description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u0438\u0434\u0435\u0438 \u0438\u0437 \u043A\u043B\u0438\u0435\u043D\u0442\u0441\u043A\u043E\u0433\u043E \u043F\u043E\u0440\u0442\u0430\u043B\u0430 (portal ideas): \u0437\u0430\u0433\u043E\u043B\u043E\u0432\u043E\u043A, \u043E\u043F\u0438\u0441\u0430\u043D\u0438\u0435, \u0441\u0442\u0430\u0442\u0443\u0441, \u043F\u0440\u0438\u043E\u0440\u0438\u0442\u0435\u0442, \u0447\u0438\u0441\u043B\u043E \u0433\u043E\u043B\u043E\u0441\u043E\u0432.",
  inputSchema: {
    status: z.enum(["backlog", "planned", "in_progress", "done"]).optional().describe("\u0424\u0438\u043B\u044C\u0442\u0440 \u043F\u043E \u0441\u0442\u0430\u0442\u0443\u0441\u0443."),
    limit: z.number().int().min(1).max(100).optional().describe("\u0421\u043A\u043E\u043B\u044C\u043A\u043E \u0437\u0430\u043F\u0438\u0441\u0435\u0439 \u0432\u0435\u0440\u043D\u0443\u0442\u044C (\u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F \u0432\u0445\u043E\u0434 \u0432 \u0430\u043A\u043A\u0430\u0443\u043D\u0442." }], isError: true };
    }
    let query = supabaseForUser(ctx).from("ideas").select("id,title,description,status,priority,source,votes,created_at").order("votes", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { ideas: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_release_notes.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_release_notes_default = defineTool2({
  name: "list_release_notes",
  title: "\u0421\u043F\u0438\u0441\u043E\u043A \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0439",
  description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 release notes \u043A\u043B\u0438\u0435\u043D\u0442\u0441\u043A\u043E\u0433\u043E \u043F\u043E\u0440\u0442\u0430\u043B\u0430: \u0432\u0435\u0440\u0441\u0438\u044F, \u0434\u0430\u0442\u0430, \u0441\u0442\u0430\u0442\u0443\u0441, \u0447\u0442\u043E \u043D\u043E\u0432\u043E\u0433\u043E.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("\u0421\u043A\u043E\u043B\u044C\u043A\u043E \u0437\u0430\u043F\u0438\u0441\u0435\u0439 \u0432\u0435\u0440\u043D\u0443\u0442\u044C (\u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F \u0432\u0445\u043E\u0434 \u0432 \u0430\u043A\u043A\u0430\u0443\u043D\u0442." }], isError: true };
    }
    const sb = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("release_notes").select("id,version,title,summary,status,released_at,tags").order("released_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { release_notes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_roadmap.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_roadmap_default = defineTool3({
  name: "list_roadmap",
  title: "Roadmap",
  description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u044D\u043B\u0435\u043C\u0435\u043D\u0442\u044B \u0434\u043E\u0440\u043E\u0436\u043D\u043E\u0439 \u043A\u0430\u0440\u0442\u044B: \u0437\u0430\u0433\u043E\u043B\u043E\u0432\u043E\u043A, \u0441\u0442\u0430\u0442\u0443\u0441, \u043A\u0432\u0430\u0440\u0442\u0430\u043B, \u043E\u043F\u0438\u0441\u0430\u043D\u0438\u0435.",
  inputSchema: {
    status: z3.enum(["planned", "in_progress", "done"]).optional().describe("\u0424\u0438\u043B\u044C\u0442\u0440 \u043F\u043E \u0441\u0442\u0430\u0442\u0443\u0441\u0443.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F \u0432\u0445\u043E\u0434 \u0432 \u0430\u043A\u043A\u0430\u0443\u043D\u0442." }], isError: true };
    }
    const sb = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = sb.from("roadmap_items").select("*").order("created_at", { ascending: false });
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { roadmap: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit_idea.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var submit_idea_default = defineTool4({
  name: "submit_idea",
  title: "\u041E\u0442\u043F\u0440\u0430\u0432\u0438\u0442\u044C \u0438\u0434\u0435\u044E",
  description: "\u0421\u043E\u0437\u0434\u0430\u0451\u0442 \u043D\u043E\u0432\u0443\u044E \u0438\u0434\u0435\u044E \u0432 \u043A\u043B\u0438\u0435\u043D\u0442\u0441\u043A\u043E\u043C \u043F\u043E\u0440\u0442\u0430\u043B\u0435 \u043E\u0442 \u0438\u043C\u0435\u043D\u0438 \u0432\u043E\u0448\u0435\u0434\u0448\u0435\u0433\u043E \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F.",
  inputSchema: {
    title: z4.string().trim().min(3).describe("\u041A\u043E\u0440\u043E\u0442\u043A\u0438\u0439 \u0437\u0430\u0433\u043E\u043B\u043E\u0432\u043E\u043A \u0438\u0434\u0435\u0438."),
    description: z4.string().trim().min(10).describe("\u041F\u043E\u0434\u0440\u043E\u0431\u043D\u043E\u0435 \u043E\u043F\u0438\u0441\u0430\u043D\u0438\u0435."),
    priority: z4.enum(["low", "medium", "high"]).optional().describe("\u041F\u0440\u0438\u043E\u0440\u0438\u0442\u0435\u0442.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, description, priority }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F \u0432\u0445\u043E\u0434 \u0432 \u0430\u043A\u043A\u0430\u0443\u043D\u0442." }], isError: true };
    }
    const sb = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("ideas").insert({ title, description, priority: priority ?? "medium", source: "client_form" }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `\u0418\u0434\u0435\u044F \u0441\u043E\u0437\u0434\u0430\u043D\u0430: ${data.id}` }],
      structuredContent: { idea: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nzjqcbuceizpcavrmgnv";
var mcp_default = defineMcp({
  name: "aleksamois-mcp",
  title: "\u0410\u043B\u0435\u043A\u0441\u0430\u043D\u0434\u0440\u0430 \u041C\u043E\u0438\u0441\u0435\u0435\u0432\u0430 \u2014 MCP",
  version: "0.1.0",
  instructions: "\u0418\u043D\u0441\u0442\u0440\u0443\u043C\u0435\u043D\u0442\u044B \u0434\u043B\u044F \u043A\u043B\u0438\u0435\u043D\u0442\u0441\u043A\u043E\u0433\u043E \u043F\u043E\u0440\u0442\u0430\u043B\u0430 aleksamois.ru. \u0418\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u0439\u0442\u0435 list_ideas, list_release_notes \u0438 list_roadmap \u0434\u043B\u044F \u0447\u0442\u0435\u043D\u0438\u044F, submit_idea \u2014 \u0447\u0442\u043E\u0431\u044B \u043F\u0440\u0435\u0434\u043B\u043E\u0436\u0438\u0442\u044C \u043D\u043E\u0432\u0443\u044E \u0438\u0434\u0435\u044E \u043E\u0442 \u0438\u043C\u0435\u043D\u0438 \u0432\u043E\u0448\u0435\u0434\u0448\u0435\u0433\u043E \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_ideas_default, list_release_notes_default, list_roadmap_default, submit_idea_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
